Ans 1.

 NumPy (Numerical Python) is a fundamental library in Python, designed to enable efficient numerical computations. It plays a crucial role in scientific computing and data analysis due to its performance, versatility, and rich ecosystem. Here's an overview of its purpose and advantages:

>Purpose of NumPy:

.Efficient Numerical Operations: NumPy provides tools for performing complex numerical operations on large datasets quickly and efficiently.

.Multidimensional Array Support: At its core is the powerful ndarray object, which enables working with multidimensional data structures.

.Foundation for Other Libraries: NumPy serves as the base for many other scientific computing libraries like SciPy, pandas, scikit-learn, and TensorFlow, ensuring compatibility and ease of integration.

>Advantages of NumPy:

1. Performance:

.Optimized for Speed: NumPy operations are implemented in C, making them significantly faster than equivalent Python loops for numerical tasks.

.Vectorized Operations: Instead of processing one element at a time, NumPy performs operations on entire arrays, eliminating the need for slow Python loops.

2. Memory Efficiency:

.Compact Arrays: NumPy arrays consume less memory compared to Python lists. For example, a NumPy array of integers is stored as contiguous blocks in memory, avoiding overhead from Python objects.

3. Broad Functionality:

.Mathematical Operations: Offers a wide array of mathematical functions, including linear algebra, Fourier transforms, and statistical computations.

.Logical Operations: Enables complex filtering, slicing, and conditional operations on arrays.

.Random Number Generation: Includes powerful tools for generating random samples from various probability distributions.

4. Flexibility and Ease of Use:

.Array Broadcasting: Simplifies operations by allowing arithmetic on arrays of different shapes without explicit reshaping.

.Indexing and Slicing: Provides advanced methods for extracting and modifying data, including boolean indexing and multidimensional slicing.

5. Compatibility with Other Tools:

. Interoperability: Works seamlessly with data analysis and visualization libraries like pandas, matplotlib, and seaborn.

.Data Formats: Supports efficient I/O operations for reading/writing arrays in formats like CSV, binary, and NumPy's .npy.

6. Scalability:

.High Dimensionality: Handles data in one-dimensional (vectors), two-dimensional (matrices), or higher-dimensional arrays with ease.

.Parallelism: Often supports multi-threaded and parallel computations via optimized backend libraries like BLAS and LAPACK.

.Enhancing Python's Capabilities:

Python, while a versatile general-purpose language, is not optimized for heavy numerical or array-based computations. NumPy fills this gap by:

1. Providing a fast and efficient array processing library.

2. Enabling concise code for numerical tasks, e.g., matrix multiplication can be done with numpy.dot(A, B) rather than verbose nested loops.

3. Offering a unified framework for scientific computing tasks that integrates seamlessly with Python's syntax and libraries.

Ans 2. 

Both np.mean() and np.average() are functions in NumPy used to compute the average of numerical data, but they differ in functionality and use cases. Here's a comparison:


1. Definition and Functionality

.np.mean():

.Computes the arithmetic mean (simple average) of the array elements.

.Does not support weights-each element is treated equally.

.Syntax: np.mean(arr, axis=None, dtype=None, keepdims=False)

Example:

In [47]:
import numpy as np

arr = np.array([1, 2, 3, 4])
np.mean(arr)  # Output: 2.5

np.float64(2.5)

.np.average():

.Computes a weighted average of the array elements if weights are provided; otherwise, behaves like np.mean().

.Syntax: np.average(arr, weights=None, axis=None, returned=False)

.weights: Array-like object specifying the weight for each element.

.returned: If True, also returns the sum of weights.


In [48]:
import numpy as np

arr = np.array([1, 2, 3, 4])
weights = np.array([1, 1, 2, 2])
np.average(arr, weights=weights)  # Output: 3.0

np.float64(2.8333333333333335)

3. When to Use Each Function:

.Use np.mean():

.When computing the arithmetic mean of an array.

.When weights are not needed, and simplicity or performance is preferred.

.Example: Finding the mean temperature of a dataset.

.Use np.average():

.When calculating a weighted mean, such as in scenarios where data points contribute unequally to the average.

.Example: Finding the weighted average score of students, where weights are the number of credits per course.

.When you need both the weighted average and the sum of weights, set returned=True.

> Example of Both Function

In [49]:
import numpy as np

data = np.array([10, 20, 30, 40])
weights = np.array([1, 2, 3, 4])

# Simple mean
mean_result = np.mean(data)  # Output: 25.0

# Weighted average
weighted_avg = np.average(data, weights=weights)  # Output: 30.0

Ans 3.

Reversing a NumPy array can be done using slicing or specific functions depending on the axis you want to reverse. Below are the methods and examples for reversing 1D and 2D arrays along different axes.


1. Reversing a 1D Array

For a 1D array, reversing means flipping the order of elements.

Method: Using slicing ([::-1])
Syntax: array[::-1]
Example:

In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print("Original:", arr)        # Output: [1 2 3 4 5]
print("Reversed:", reversed_arr)  # Output: [5 4 3 2 1]

Original: [1 2 3 4 5]
Reversed: [5 4 3 2 1]


2. Reversing a 2D Array
For a 2D array, you can reverse rows, columns, or both.

Reversing Rows
Reverses the order of rows along axis 0.

Method: array[::-1, :]

. Example

In [51]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
reversed_rows = arr[::-1, :]
print("Original:\n", arr)
print("Reversed Rows:\n", reversed_rows)

Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed Rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


Reversing Both Rows and Columns
Reverses the entire 2D array.

Method: array[::-1, ::-1]
Example:

In [52]:
reversed_all = arr[::-1, ::-1]
print("Reversed Both Rows and Columns:\n", reversed_all)

Reversed Both Rows and Columns:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


3. Using np.flip for General Reversals:

The np.flip function can reverse an array along any axis.

1D Array

In [53]:
flipped = np.flip(arr)
print("Flipped 1D Array:", flipped)

Flipped 1D Array: [[9 8 7]
 [6 5 4]
 [3 2 1]]


2D Array
Reverse along rows (axis=0):

In [54]:
flipped_rows = np.flip(arr, axis=0)
print("Flipped Rows:\n", flipped_rows)

Flipped Rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


. Reverse along colums(axis=1):

In [55]:
flipped_cols = np.flip(arr,axis=1)
print("flipped colums:\n", flipped_cols)

flipped colums:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


Reverse Entire Array

In [56]:
flipped_all = np.flip(arr)
print("Flipped Entire Array:\n", flipped_all)

Flipped Entire Array:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


Ans 5.

Determining the Data Type of Elements in a NumPy Array

The data type of elements in a NumPy array is stored in its dtype attribute. You can determine the data type using:

1. array.dtype: Returns the data type of the array elements.

In [57]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.dtype) # Output: int32

int32


2. type(): Determines the data type of a specific element in the array.

In [58]:
print(type(arr[0])) # Output: <class 'numpy.int32'>

<class 'numpy.int32'>


3. np.issubdtype(): Checks if the array's data type is a subtype of a given type.

In [59]:
print(np.issubdtype(arr.dtype, np.integer))  # Output: True
print(np.issubdtype(arr.dtype, np.float64))  # Output: False

True
False


>Importance of Data Types in NumPy

Data types in NumPy (e.g., int32, float64) are critical for memory management and performance optimization in numerical computing.

1. Memory Management

.Efficient Storage: NumPy arrays use fixed-size data types, reducing memory overhead compared to Python lists, which store data as objects with additional metadata.

.Example:
A Python list of integers takes significantly more memory than a NumPy array with int32 or int64 elements.

In [60]:
import numpy as np
import sys

py_list = [1, 2, 3]
np_array = np.array([1, 2, 3], dtype=np.int32)

print(sys.getsizeof(py_list[0]) * len(py_list))  # Size of Python list
print(np_array.nbytes)  # Size of NumPy array

84
12


.Customizable Precision: Choosing the appropriate data type (e.g., float32 instead of float64) minimizes memory usage without sacrificing accuracy for specific applications.

2. Performance Optimization

.Vectorized Operations: NumPy arrays are optimized for vectorized operations, and fixed-size data types allow computations to be performed directly at the hardware level using SIMD (Single Instruction, Multiple Data).

.Smaller data types (int8, float32) process faster since they require less bandwidth and fit more elements in memory.

In [61]:
arr1 = np.random.rand(1_000_000).astype(np.float32)
arr2 = np.random.rand(1_000_000).astype(np.float64)

%timeit np.sum(arr1)  # Faster due to float32
%timeit np.sum(arr2)  # Slower due to float64

310 μs ± 13.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
396 μs ± 37.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


.Avoiding Type Conversion: Using a consistent data type prevents unnecessary type conversions, which can slow down computations.

In [62]:
arr = np.array([1, 2, 3], dtype=np.float32)
result = arr + 2.5  # No type conversion needed

3. Accuracy and Range
.Range of Values: Certain data types have specific ranges (e.g., int8 supports -128 to 127). Choosing the wrong type can lead to overflow or underflow errors.

.Precision: Applications requiring high precision (e.g., scientific simulations) may require float64 or complex128.

4. Compatibility with External Tools

.Many scientific and machine learning tools require specific data types for compatibility. For example:

.TensorFlow prefers float32 for model training due to GPU optimization.

.Pandas often interacts with NumPy arrays, and incorrect data types can lead to inefficiencies.

>Best Practices
1. Choose the Smallest Data Type That Meets Your Needs:

.For integers: Use int8, int16, or int32 based on the expected range.

.For floating-point numbers: Use float32 for lower precision and float64 for high precision.

In [63]:
small_array = np.array([1, 2, 3], dtype=np.int8)  # Efficient storage

2. Be Mindful of Mixed Types:

.Mixing data types in operations may lead to unexpected behavior or conversions.

In [64]:
arr = np.array([1.0, 2, 3])  # Converts to float64

3. Inspect and Convert Data Types as Needed:

.Use astype() to convert:

In [65]:
arr = arr.astype(np.float32)

Ans 4.

>Definition of ndarray in NumPy

An ndarray (short for N-dimensional array) is the primary data structure in NumPy. It represents a collection of elements, all of the same data type, indexed by a tuple of non-negative integers. ndarray is designed for efficient numerical computations and can handle multi-dimensional data.
Key Features of ndarray

1. Homogeneous Data:

.All elements in an ndarray must be of the same data type (e.g., int32, float64), which ensures consistency and allows for efficient memory use and computation.

2. Multi-dimensional:

.Supports arrays of arbitrary dimensions (1D, 2D, 3D, etc.), making it ideal for representing scalars, vectors, matrices, and tensors.

3. Efficient Memory Layout:

.Uses a contiguous memory block for storage, enabling faster access and manipulation compared to Python lists.

4. Rich Functionalities:

.Supports mathematical operations (e.g., addition, subtraction, multiplication) applied element-wise.

.Includes methods for slicing, reshaping, aggregations (e.g., mean, sum), and more.

5. Data Type Flexibility:

.Allows specifying precise data types (dtype), such as int8, float32, or complex128, offering control over precision and memory usage.

6. Broadcasting:

.Automatically expands arrays with different shapes to enable element-wise operations without explicit looping or reshaping.

7. Vectorized Operations:

.Operates on entire arrays without requiring explicit loops, which is both faster and more concise.

8. Interoperability:

Works seamlessly with other scientific libraries, such as pandas, SciPy, and TensorFlow.

>Example Comparsion

In [66]:
# Create a list
py_list = [1, 2, 3]

# Element-wise operation (requires looping)
squared = [x**2 for x in py_list]
print(squared)  # Output: [1, 4, 9]

[1, 4, 9]


NumPy ndarry:

In [67]:
import numpy as np

# Create an ndarray
arr = np.array([1, 2, 3])

# Element-wise operation (vectorized)
squared = arr**2
print(squared)  # Output: [1 4 9]

[1 4 9]


Multi-dimensional Example

Python lists require nesting and explicit loops:

In [68]:
# Nested list
nested_list = [[1, 2], [3, 4]]
transposed = [[row[i] for row in nested_list] for i in range(len(nested_list[0]))]
print(transposed)  # Output: [[1, 3], [2, 4]]

[[1, 3], [2, 4]]


With NumPy, you can use built-in function:

In [69]:
# 2D array
matrix = np.array([[1, 2], [3, 4]])
transposed = matrix.T
print(transposed)  # Output: [[1 3]
                   #          [2 4]]

[[1 3]
 [2 4]]


When to Use ndarray

.For numerical computations, data analysis, or tasks requiring performance and memory efficiency.

.When working with multi-dimensional data like matrices or tensors.

.When scalability, precision, or compatibility with scientific libraries is required.

Ans 6.

Performance Benefits of NumPy Arrays over Python Lists

NumPy arrays (ndarray) offer significant performance advantages over Python lists when handling large-scale numerical operations. These benefits arise from efficient memory management, vectorized operations, and optimized low-level implementations. Here’s a detailed analysis:

1. Memory Efficiency

.Compact Storage:

.NumPy arrays use a contiguous block of memory and store elements in fixed-size data types (e.g., int32, float64). This reduces the memory overhead compared to Python lists, where each element is a Python object with additional metadata.

.Example:

In [70]:
import numpy as np
import sys

py_list = [1, 2, 3, 4, 5]
np_array = np.array([1, 2, 3, 4, 5])

print("List size:", sys.getsizeof(py_list[0]) * len(py_list))  # Output: 140 bytes (Python list)
print("NumPy size:", np_array.nbytes)                        # Output: 20 bytes (NumPy array)

List size: 140
NumPy size: 40


.Scalability:

.As data scales up, the fixed-type storage of NumPy arrays becomes increasingly beneficial.

2. Faster Execution with Vectorized Operations

.Element-wise Operations:

.NumPy arrays perform operations directly on the entire array using highly optimized C and Fortran libraries, avoiding the need for Python-level loops.

Example:

In [71]:
import numpy as np
import time

size = 10**6
py_list = list(range(size))
np_array = np.arange(size)

# Python list (manual loop)
start = time.time()
py_result = [x * 2 for x in py_list]
print("Python list time:", time.time() - start)

# NumPy array (vectorized)
start = time.time()
np_result = np_array * 2
print("NumPy array time:", time.time() - start)

Python list time: 0.03943133354187012
NumPy array time: 0.0020956993103027344


.Broadcasting:

.NumPy supports broadcasting, allowing operations on arrays of different shapes without explicit loops.

In [72]:
arr = np.array([1, 2, 3])
print(arr + 10)  # Output: [11 12 13]

[11 12 13]


3. Efficient Use of CPU and SIMD

.NumPy leverages SIMD (Single Instruction, Multiple Data) instructions, allowing the CPU to perform operations on multiple elements simultaneously.

.NumPy’s low-level implementation uses efficient BLAS (Basic Linear Algebra Subprograms) and LAPACK libraries for numerical operations.

4. Precompiled Functions

.Functions like np.sum(), np.mean(), and others are precompiled and implemented in C, making them significantly faster than equivalent Python functions.

Example:

In [73]:
import numpy as np

size = 10**6
py_list = list(range(size))
np_array = np.arange(size)

# Python sum
start = time.time()
py_sum = sum(py_list)
print("Python sum time:", time.time() - start)

# NumPy sum
start = time.time()
np_sum = np.sum(np_array)
print("NumPy sum time:", time.time() - start)

Python sum time: 0.006178617477416992
NumPy sum time: 0.0008208751678466797


5. Multi-dimensional Data Handling

.NumPy efficiently handles multi-dimensional data without nested loops, unlike Python lists, which require complex nesting and operations.

Example:

In [74]:
# Matrix multiplication
import numpy as np

A = np.random.rand(1000, 1000)
B = np.random.rand(1000, 1000)

# Fast matrix multiplication
C = np.dot(A, B)

Ans 7.

In NumPy, vstack() and hstack() are used to stack arrays along different axes. Here's a detailed comparison with examples:

1. numpy.vstack()

.Purpose: Stacks arrays vertically (row-wise).

.Axis of stacking: Adds arrays along a new vertical axis.

.Requirements: The arrays must have the same number of columns (shapes along the second dimension must match).

Example:

In [75]:
import numpy as np

# Creating two arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])

# Using vstack()
result_vstack = np.vstack((array1, array2))

print("Result of vstack:")
print(result_vstack)

Result of vstack:
[[1 2]
 [3 4]
 [5 6]]


2. numpy.hstack()

.Purpose: Stacks arrays horizontally (column-wise).

.Axis of stacking: Adds arrays along a new horizontal axis.

.Requirements: The arrays must have the same number of rows (shapes along the first dimension must match).

In [76]:
# Using the same arrays
result_hstack = np.hstack((array1, array2.T))  # Note: array2 is transposed to match rows

print("Result of hstack:")
print(result_hstack)

Result of hstack:
[[1 2 5]
 [3 4 6]]


Combined Demonstration:

In [77]:
# Demonstrating both
result_vstack = np.vstack((array1, array2))
result_hstack = np.hstack((array1, array2.T))

print("vstack result:\n", result_vstack)
print("hstack result:\n", result_hstack)

vstack result:
 [[1 2]
 [3 4]
 [5 6]]
hstack result:
 [[1 2 5]
 [3 4 6]]


Ans 8.

In NumPy, fliplr() and flipud() are used to reverse the order of elements in arrays along specific dimensions. Here's a breakdown of their differences, effects, and examples.

1. numpy.fliplr()

.Purpose: Flips the array left to right (reverses the order of columns).

.Effect on Dimensions: Operates along the last axis (axis=1).

.Requirements: The array must be at least 2-dimensional.

Behavior:

.Columns are reversed for each row, but the row order remains unchanged.

Example:

In [78]:
import numpy as np

# Creating a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Applying fliplr()
result_fliplr = np.fliplr(array)

print("Original array:")
print(array)

print("\nResult of fliplr:")
print(result_fliplr)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Result of fliplr:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


2. numpy.flipud()

.Purpose: Flips the array upside down (reverses the order of rows).

.Effect on Dimensions: Operates along the first axis (axis=0).

.Requirements: The array must be at least 2-dimensional.

Behavior:
.Rows are reversed for the entire array, but the column order remains unchanged.

Example:

For Higher Dimensions:

For arrays with more than two dimensions:

.fliplr() reverses the second-to-last axis (e.g., for a 3D array, it flips along the axis of columns in each 2D "slice").

.flipud() reverses the first axis (e.g., flips the "slices" along the vertical axis).

Example with a 3D array:

In [79]:
array_3d = np.array([[[1, 2], [3, 4]], 
                     [[5, 6], [7, 8]]])

print("Original 3D array:")
print(array_3d)

print("\nfliplr result:")
print(np.fliplr(array_3d))  # Flips columns of each 2D slice

print("\nflipud result:")
print(np.flipud(array_3d))  # Flips the 2D slices along the vertical axis

Original 3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

fliplr result:
[[[3 4]
  [1 2]]

 [[7 8]
  [5 6]]]

flipud result:
[[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


Summary:

.Use fliplr() to reverse the order of columns.

.Use flipud() to reverse the order of rows.

Both are intuitive methods for manipulating arrays, particularly useful in image processing and data visualization tasks.

Ans 9.

The numpy.array_split() function is used to split an array into multiple sub-arrays along a specified axis. Unlike numpy.split(), which requires that the array can be evenly split, array_split() can handle uneven splits gracefully.

Key Features of array_split()

1. Uneven Splits:

.If the array cannot be split evenly into the specified number of sub-arrays, array_split() distributes the elements as evenly as possible.

.Sub-arrays will differ in size, with the first few sub-arrays being larger if the split is uneven.

2. Arguments:

.ary: The array to split. 

.indices_or_sections:

.If an integer, it specifies the number of equal or nearly equal sub-arrays to create.

.If a list or array of indices, it specifies the boundaries at which to split the array.

.axis (optional): The axis along which the array should be split (default is 0).

3. Return:

.A list of sub-arrays.

Example:

1. Uneven Splitting with integer input

In [80]:
import numpy as np

# Original array
array = np.array([1, 2, 3, 4, 5, 6, 7])

# Splitting into 3 parts
result = np.array_split(array, 3)

print("Original array:", array)
print("Split result:", result)

Original array: [1 2 3 4 5 6 7]
Split result: [array([1, 2, 3]), array([4, 5]), array([6, 7])]


2. Splitting with Specific indices

In [81]:
# Splitting using indices
result = np.array_split(array, [2, 5])

print("Split result with indices:", result)

Split result with indices: [array([1, 2]), array([3, 4, 5]), array([6, 7])]


3. Splitting Along a Specific Axis

In [82]:
# 2D array
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

# Splitting into 2 parts along axis 1 (columns)
result = np.array_split(array_2d, 2, axis=1)

print("Original 2D array:\n", array_2d)
print("\nSplit result along columns:")
print(result)

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Split result along columns:
[array([[1, 2],
       [4, 5],
       [7, 8]]), array([[3],
       [6],
       [9]])]


Handling Uneven Splits

.If the total number of elements cannot be evenly divided by the number of requested splits, the leftover elements are distributed to the initial sub-arrays in the result.

.This ensures the sizes of the sub-arrays differ by at most one element.

Example of Uneven Splitting with 2D Array:

In [83]:
# 2D array with uneven split
result = np.array_split(array_2d, 4, axis=0)

print("\nSplit result with uneven row distribution:")
print(result)


Split result with uneven row distribution:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([], shape=(0, 3), dtype=int64)]


Key Points

1. Comparison with split():

.numpy.split() raises an error if the split is uneven.

.numpy.array_split() handles uneven splits automatically.

2. Empty Sub-Arrays:

.If there are more sections than elements in the array, some sub-arrays may be empty.

3. Flexibility:

Allows splitting using both fixed number of parts or specific indices.

Ans 10.

Vectorization and Broadcasting in NumPy

Vectorization and broadcasting are core concepts in NumPy that contribute to efficient array operations. They enable concise, readable code and take advantage of optimized low-level implementations for performance.

1. Vectorization

Vectorization refers to performing operations on entire arrays (or vectors) without the need for explicit loops. This is achieved by leveraging NumPy's internal implementation, which uses optimized C code to operate directly on arrays.

Key Features:

.Eliminates explicit loops in Python code.

.Enhances performance by utilizing low-level optimizations.

.Makes code more concise and readable.

Example Without Vectorization:

In [84]:
import numpy as np

# Compute the square of each element in a list using a loop
data = [1, 2, 3, 4, 5]
squared = []
for x in data:
    squared.append(x**2)

print("Squared (loop):", squared)

Squared (loop): [1, 4, 9, 16, 25]


With Vectorization:

In [85]:
# Using NumPy vectorized operations
data = np.array([1, 2, 3, 4, 5])
squared = data**2  # Element-wise squaring

print("Squared (vectorized):", squared)

Squared (vectorized): [ 1  4  9 16 25]


2. Broadcasting

Broadcasting refers to NumPy's ability to perform arithmetic operations on arrays of different shapes by automatically expanding one of them to match the shape of the other.

Key Features:

.Avoids the need for manual array resizing.

.Efficiently computes operations across mismatched array shapes.

.Works by extending the smaller array along its missing dimensions.

Rules for Broadcasting:

1. If the dimensions of the arrays are unequal, NumPy aligns them by adding dimensions of size 1 to the left of the smaller array.

2. If the sizes along any dimension are not the same, they must either be equal or one of them must be 1.

3. The array with size 1 in a dimension is "stretched" to match the size of the other array along that dimension.

Example of Broadcasting:

In [86]:
# Adding a scalar to a 1D array
array = np.array([1, 2, 3])
result = array + 5

print("Broadcasting scalar addition:", result)

Broadcasting scalar addition: [6 7 8]


Example with Arrays of Different Shapes: 

In [87]:
# Adding a 1D array to a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_1d = np.array([10, 20, 30])

result = array_2d + array_1d

print("Broadcasting with arrays:\n", result)

Broadcasting with arrays:
 [[11 22 33]
 [14 25 36]]


Advantages of Vectorization and Broadcasting

1. Performance:

.Operations are implemented in C, leading to significant speed-ups compared to Python loops.

2. Code Readability:

.Reduces the need for explicit loops and array manipulations.

3. Memory Efficiency:

.Avoids creating intermediate copies of arrays by operating directly on them.

Practical Questions:

Ans 1.

Here is the 3x3 NumPy array with random integers between 1 and 100 and its transposed version (interchanged rows and columns):

Original Array:

[[94 56 80]
 [41 55 18]
 [34 70 49]]

Transposed Array:

[[94 41 34]
 [56 55 70]
 [80 18 49]]

Ans 2.

Here are the results of generating a 1D NumPy array and reshaping it into different forms:

1D Array (10 element):

[ 1  2  3  4  5  6  7  8  9 10]

.Reshaped into 2x5 Array:

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped into 5x2 Array:

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

Ans 3. 

Original 4x4 Array (with random float values):

[[0.58827261 0.95959024 0.61980797 0.1546133 ]
 [0.99288622 0.22742135 0.8612033  0.07464458]
 [0.16041453 0.71797218 0.89055504 0.08740898]
 [0.60049334 0.10968417 0.37460467 0.82299827]]

6x6 Array with a Boder of Zeros:

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.58827261 0.95959024 0.61980797 0.1546133  0.        ]
 [0.         0.99288622 0.22742135 0.8612033  0.07464458 0.        ]
 [0.         0.16041453 0.71797218 0.89055504 0.08740898 0.        ]
 [0.         0.60049334 0.10968417 0.37460467 0.82299827 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]

Ans 4.

You can create an array of integers from 10 to 60 with a step of 5 using NumPy's np.arange() function. Here's how you can do it:

In [88]:
import numpy as np

array = np.arange(10, 61, 5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


Explanation:

np.arange(start, stop, step) generates values starting from start (10), up to (but not including) stop (61), with a step of 5.

Ans 5.

You can create a NumPy array of strings and then apply various string transformations such as uppercase, lowercase, title case, etc., using the .vectorize() method for element-wise operations on the array. Here’s an example:

In [89]:
import numpy as np

# Create the NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
upper_case = np.char.upper(arr)  # Convert to uppercase
lower_case = np.char.lower(arr)  # Convert to lowercase
title_case = np.char.title(arr)  # Convert to title case
capitalize_case = np.char.capitalize(arr)  # Capitalize the first letter of each string

# Print the results
print("Original:", arr)
print("Uppercase:", upper_case)
print("Lowercase:", lower_case)
print("Title case:", title_case)
print("Capitalize case:", capitalize_case)

Original: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']
Capitalize case: ['Python' 'Numpy' 'Pandas']


Explanation:

.np.char.upper(arr) converts all characters to uppercase.

.np.char.lower(arr) converts all characters to lowercase.

.np.char.title(arr) capitalizes the first letter of each word (title case).

.np.char.capitalize(arr) capitalizes the first letter of the entire string.

These operations are applied element-wise on the NumPy array of strings.





Ans 6. 

You can generate a NumPy array of words and insert a space between each character of every word using the np.char.add() function. This function can be used to concatenate a space (" ") between each character of the words in the array. Here's how you can do it:

Ans 7. 

You can perform element-wise operations like addition, subtraction, multiplication, and division on two 2D NumPy arrays using standard arithmetic operators. Here's an example that demonstrates all of these operations:

In [90]:
import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[6, 5, 4], [3, 2, 1]])

# Element-wise addition
addition = arr1 + arr2

# Element-wise subtraction
subtraction = arr1 - arr2

# Element-wise multiplication
multiplication = arr1 * arr2

# Element-wise division
# Note: We use np.divide to handle division, which avoids division by zero errors
division = np.divide(arr1, arr2)

# Print the results
print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)

print("\nElement-wise addition:")
print(addition)

print("\nElement-wise subtraction:")
print(subtraction)

print("\nElement-wise multiplication:")
print(multiplication)

print("\nElement-wise division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[6 5 4]
 [3 2 1]]

Element-wise addition:
[[7 7 7]
 [7 7 7]]

Element-wise subtraction:
[[-5 -3 -1]
 [ 1  3  5]]

Element-wise multiplication:
[[ 6 10 12]
 [12 10  6]]

Element-wise division:
[[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


Ans 8.

You can create a 5x5 identity matrix using NumPy's np.eye() function, and then extract its diagonal elements using the np.diagonal() method. Here's how you can do it:

In [91]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = identity_matrix.diagonal()

# Print the results
print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


Ans 9.

To generate a NumPy array of 100 random integers between 0 and 1000 and then find all the prime numbers in the array, we can follow these steps:

..Generate the random integers using np.random.randint().

.Check each number for primality using a helper function.

.Filter and display the prime numbers.

Here's the code:

In [92]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Find prime numbers in the array
primes = [num for num in random_integers if is_prime(num)]

# Display the result
print("Random integers:", random_integers)
print("\nPrime numbers:", primes)

Random integers: [935 677 300 387  80 747 644 516  67 585 725 301 548 541 436 445 547 991
  22 982 643 323 863 880 386 225  85 491 345 122 255 972  96 498 436 241
 497 893 168 704 948 276 496 260 291 919 166 908 695 824 276 227 332 474
 610 194 836 970 780 309 665 732 883 255 252 307 221 822 929 235 660 400
 329 780   5 302 848 484 474 997 845 424   0 400 461 561 959  68 167 727
 600 404 809 946 276 192 329 340 924 776]

Prime numbers: [np.int32(677), np.int32(67), np.int32(541), np.int32(547), np.int32(991), np.int32(643), np.int32(863), np.int32(491), np.int32(241), np.int32(919), np.int32(227), np.int32(883), np.int32(307), np.int32(929), np.int32(5), np.int32(997), np.int32(461), np.int32(167), np.int32(727), np.int32(809)]


Ans 10.

To create a NumPy array representing daily temperatures for a month (30 days) and calculate the weekly averages, follow these steps:

.Generate a random array of temperatures for 30 days.

.Reshape the array to represent 4 weeks of data (7 days per week, with 2 extra days in the last week).

.Calculate the average temperature for each week.

Here's the code:

In [ ]:
import numpy as np

# Generate a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(15, 35, size=30)  # temperatures between 15 and 35 degrees Celsius

# Reshape the array into 4 weeks (7 days per week, and the last week may have 2 days)
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Calculate the weekly average temperature
weekly_averages = weekly_temperatures.mean(axis=1)

# Display the results
print("Daily Temperatures for the Month (30 days):")
print(daily_temperatures)

print("\nWeekly Temperatures (4 weeks, 7 days each):")
print(weekly_temperatures)

print("\nWeekly Average Temperatures:")
print(weekly_averages)
